export const menuData = [
    { name: "Home", route: "/" },
    { name: "About Us", route: "/about" },
    { name: 'Our Manufacturing Range', route: '/manufacturing-ranges/power-control-centre' },
    // { name: 'Manufacturing Facility Machinery', route: '/manufacturing-facility-machinery' },
    { name: 'Plant and Machinery', route: '/plant-and-machinery' },
    { name: 'Our Clients', route: '/our-clients' },
    { name: 'Career', route: '/career' },
    { name: 'Quality', route: '/quality' },
    { name: 'Projects', route: '/projects' },
    // {
    //     name: "Electrical Automation",
    //     id: 'electrical-automation',
    //     product: true,
    //     subMenu: [
    //         { name: "PLC Control Panel", route: "/category/electrical-automation/plc-control-panel" },
    //         { name: "HMI Touch Panel", route: "/category/electrical-automation/hmi-touch-panel" },
    //         { name: "SCADA System", route: "/category/electrical-automation/scada-system" },
    //         { name: "Motor Control Centre", route: "/category/electrical-automation/motor-control-centre" },
    //         { name: "VFD Drive", route: "/category/electrical-automation/vfd-drive" },
    //         { name: "Soft Starter", route: "/category/electrical-automation/soft-starter" },
    //         { name: "Electrical Control Panel", route: "/category/electrical-automation/electrical-control-panel" },
    //         { name: "Automation Control Panel", route: "/category/electrical-automation/automation-control-panel" },
    //         { name: "Remote I/O Module", route: "/category/electrical-automation/remote-io-module" },
    //     ],
    // },
    // {
    //     name: "Panel Manufacturing",
    //     id: 'panel-manufacturing',
    //     product: true,
    //     subMenu: [
    //         { name: "Electrical Distribution Board", route: "/category/panel-manufacturing/electrical-distribution-board" },
    //         { name: "Motor Control Panel", route: "/category/panel-manufacturing/motor-control-panel" },
    //         { name: "Power Distribution Unit", route: "/category/panel-manufacturing/power-distribution-unit" },
    //         { name: "Bus Duct", route: "/category/panel-manufacturing/bus-duct" },
    //         { name: "Electrical Control Panel", route: "/category/panel-manufacturing/electrical-control-panel" },
    //         { name: "Automation Panel", route: "/category/panel-manufacturing/automation-panel" },
    //         { name: "LV Switchboard", route: "/category/panel-manufacturing/lv-switchboard" },
    //         { name: "MV Switchgear", route: "/category/panel-manufacturing/mv-switchgear" },
    //         { name: "Electrical Panel Board", route: "/category/panel-manufacturing/electrical-panel-board" },
    //         { name: "Customized Panel", route: "/category/panel-manufacturing/customized-panel" },
    //     ],
    // },
    // {
    //     name: "EPC Contracts",
    //     product: true,
    //     id: 'epc-contracts',
    //     subMenu: [
    //         { name: "Turnkey Project Solutions", route: "/category/epc-contracts/turnkey-project-solutions" },
    //         { name: "Electrical Infrastructure Development", route: "/category/epc-contracts/electrical-infrastructure-development" },
    //         { name: "Automation and Control System Integration", route: "/category/epc-contracts/automation-and-control-system-integration" },
    //         { name: "Electrical Building Services", route: "/category/epc-contracts/electrical-building-services" },
    //         { name: "Renewable Energy System Integration", route: "/category/epc-contracts/renewable-energy-system-integration" },
    //         { name: "Electrical Substation Development", route: "/category/epc-contracts/electrical-substation-development" },
    //         { name: "Transmission and Distribution Line Construction", route: "/category/epc-contracts/transmission-and-distribution-line-construction" },
    //         { name: "Electrical System Testing and Commissioning", route: "/category/epc-contracts/electrical-system-testing-and-commissioning" },
    //         { name: "Energy Efficiency Solution", route: "/category/epc-contracts/energy-efficiency-solution" },
    //         { name: "Sustainability Solution", route: "/category/epc-contracts/sustainability-solution" },
    //     ],
    // },
    // { name: "Blogs", route: "/blogs" },
    { name: "Contact Us", route: "/contact-us" },
];
